/* 
  file summary: seed dataset for vessel corrective and preventive action (capa) items.
  responsibilities: provides realistic, maritime-accurate mock capa items linked to physical inspections for all fleet vessels.
  role in system: loaded by useMapStore.ts on initial state instantiation.
*/

import { CapaItem } from '../types/capa';

export const MOCK_CAPA_ITEMS: CapaItem[] = [
  {
    id: 'CAPA-118',
    vesselName: 'MV Pacific Endeavour',
    vesselId: 'VESSEL-001',
    checklistId: 'INS-03',
    checklistItemTitle: 'Liferaft hydrostatic release units',
    title: 'Replace port-side liferaft HRU & update service log',
    findingDescription: 'Port-side liferaft HRU service date exceeded by 3 weeks. Replacement unit on order; corrective action required before sailing.',
    owner: 'Northwind Marine Technical Dept',
    dueDate: '25 Sep 2026',
    status: 'Open',
    inspectorNotes: 'Original survey finding recorded on 18 Sep 2026. Awaiting delivery receipt and re-inspection photo of installed unit.',
    createdDate: '18 Sep 2026',
    evidences: [
      {
        id: 'EV-103',
        title: 'Liferaft HRU tag photo',
        type: 'Photo',
        fileName: 'hru_tag_port.jpg',
        fileSize: '3.1 MB',
        uploadedAt: '18 Sep 2026 14:20',
        uploadedBy: 'Inspector Marcus Vance',
      },
    ],
  },
  {
    id: 'CAPA-120',
    vesselName: 'MV Pacific Endeavour',
    vesselId: 'VESSEL-001',
    checklistId: 'INS-02',
    checklistItemTitle: 'Fire-fighting equipment and fixed systems',
    title: 'Recalibrate emergency fire pump discharge pressure relief valve',
    findingDescription: 'Emergency fire pump pressure gauge registered 0.5 bar below threshold during annual performance test.',
    owner: 'Northwind Technical Fleet Ops',
    dueDate: '29 Sep 2026',
    status: 'Under Re-Inspection',
    inspectorNotes: 'Class surveyor completed initial bench test. Final verification pending on-site sea trial.',
    createdDate: '19 Sep 2026',
    lastInspectedDate: '21 Sep 2026',
    evidences: [
      {
        id: 'EV-120',
        title: 'Bench test calibration certificate',
        type: 'Document',
        fileName: 'fire_pump_relief_cert.pdf',
        fileSize: '1.1 MB',
        uploadedAt: '21 Sep 2026 09:15',
        uploadedBy: 'Chief Engineer T. Lawson',
      },
    ],
  },
  {
    id: 'CAPA-114',
    vesselName: 'MV Pacific Endeavour',
    vesselId: 'VESSEL-001',
    checklistId: 'INS-04',
    checklistItemTitle: 'Deck cargo securing arrangements',
    title: 'Update cargo securing manual revision & lashing certs',
    findingDescription: 'Deck cargo securing manual copy on bridge missing latest class approval stamp.',
    owner: 'Northwind Marine',
    dueDate: '12 Sep 2026',
    status: 'Verified & Closed',
    inspectorNotes: 'Re-inspected on 15 Sep 2026. Approved manual stamp verified and endorsed copy uploaded.',
    createdDate: '10 Sep 2026',
    lastInspectedDate: '15 Sep 2026',
    evidences: [
      {
        id: 'EV-114',
        title: 'Class endorsed manual page scan',
        type: 'Document',
        fileName: 'csm_class_stamp_2026.pdf',
        fileSize: '1.2 MB',
        uploadedAt: '15 Sep 2026 11:05',
        uploadedBy: 'Inspector Marcus Vance',
      },
    ],
  },
  {
    id: 'CAPA-112',
    vesselName: 'MV Atlantic Ocean',
    vesselId: 'VESSEL-005',
    checklistId: 'INS-02',
    checklistItemTitle: 'Fire-fighting equipment and fixed systems',
    title: 'Servicing of engine room CO2 release valve pressure gauge',
    findingDescription: 'Engine room CO2 battery pressure gauge reading slightly below green band threshold.',
    owner: 'Northwind Marine Technical Ops',
    dueDate: '28 Sep 2026',
    status: 'Under Re-Inspection',
    inspectorNotes: 'Service technician replaced gauge on 20 Sep 2026. On-site re-inspection in progress.',
    createdDate: '12 Sep 2026',
    lastInspectedDate: '21 Sep 2026',
    evidences: [
      {
        id: 'EV-112',
        title: 'CO2 gauge service receipt',
        type: 'Document',
        fileName: 'co2_gauge_service_cert.pdf',
        fileSize: '890 KB',
        uploadedAt: '20 Sep 2026 09:30',
        uploadedBy: 'Chief Engineer H. Nilsson',
      },
    ],
  },
  {
    id: 'CAPA-115',
    vesselName: 'MV Atlantic Ocean',
    vesselId: 'VESSEL-005',
    checklistId: 'INS-06',
    checklistItemTitle: 'MARPOL Annex I · Pollution Prevention',
    title: 'Calibrate oily water separator (OWS) 15 ppm alarm sensor',
    findingDescription: 'OWS 15 ppm monitor calibration certificate due for annual renewal. Spare sensor cell installed.',
    owner: 'Northwind Marine Technical Ops',
    dueDate: '02 Oct 2026',
    status: 'Open',
    inspectorNotes: 'Flag state inspector requested updated calibration report prior to departure.',
    createdDate: '17 Sep 2026',
    evidences: [
      {
        id: 'EV-115',
        title: 'OWS monitor sensor calibration test sheet',
        type: 'Document',
        fileName: 'ows_calibration_report_2026.pdf',
        fileSize: '620 KB',
        uploadedAt: '18 Sep 2026 10:15',
        uploadedBy: 'Second Engineer R. Tanaka',
      },
    ],
  },
  {
    id: 'CAPA-109',
    vesselName: 'MV Southern Cross',
    vesselId: 'VESSEL-004',
    checklistId: 'INS-01',
    checklistItemTitle: 'Life-saving appliances — stowage and condition',
    title: 'Renew starboard lifeboat embarkation ladder rungs',
    findingDescription: 'Top two rungs of starboard embarkation ladder showing signs of salt wear.',
    owner: 'Northwind Marine Technical Dept',
    dueDate: '30 Sep 2026',
    status: 'Open',
    inspectorNotes: 'Raised during routine physical survey. Replacement ladder ordered from supplier.',
    createdDate: '14 Sep 2026',
    evidences: [
      {
        id: 'EV-109',
        title: 'Starboard embarkation ladder wear photo',
        type: 'Photo',
        fileName: 'ladder_rungs_wear.jpg',
        fileSize: '2.8 MB',
        uploadedAt: '14 Sep 2026 15:40',
        uploadedBy: 'Inspector Marcus Vance',
      },
    ],
  },
  {
    id: 'CAPA-116',
    vesselName: 'MV Southern Cross',
    vesselId: 'VESSEL-004',
    checklistId: 'INS-05',
    checklistItemTitle: 'Crew familiarity — muster and abandon ship',
    title: 'Update ISM emergency drill log sign-off matrix',
    findingDescription: 'Muster drill attendance sheet missing master endorsement signature for August drill.',
    owner: 'Northwind Marine Technical Dept',
    dueDate: '24 Sep 2026',
    status: 'Rectification Required',
    inspectorNotes: 'Audit observation logged during safety management survey.',
    createdDate: '16 Sep 2026',
    evidences: [
      {
        id: 'EV-116',
        title: 'Muster drill sheet scan',
        type: 'Document',
        fileName: 'muster_drill_sheet_aug2026.pdf',
        fileSize: '410 KB',
        uploadedAt: '16 Sep 2026 16:30',
        uploadedBy: 'Chief Mate D. Kovacs',
      },
    ],
  },
  {
    id: 'CAPA-121',
    vesselName: 'MV Coral Titan',
    vesselId: 'VESSEL-002',
    checklistId: 'INS-03',
    checklistItemTitle: 'DP3 System Redundancy & Thruster Performance',
    title: 'Recalibrate DP thruster #3 feedback sensor',
    findingDescription: 'Thruster #3 feedback signal experienced minor noise spike during DP trial.',
    owner: 'Northwind Marine Technical Dept',
    dueDate: '10 Oct 2026',
    status: 'Under Re-Inspection',
    inspectorNotes: 'Kongsberg technician replaced sensor module. Sea trial verification pending.',
    createdDate: '15 Sep 2026',
    evidences: [
      {
        id: 'EV-121',
        title: 'Kongsberg DP thruster feedback test report',
        type: 'Document',
        fileName: 'dp_thruster3_sensor_service.pdf',
        fileSize: '1.4 MB',
        uploadedAt: '16 Sep 2026 11:20',
        uploadedBy: 'Kongsberg Service Engineer',
      },
    ],
  },
  {
    id: 'CAPA-122',
    vesselName: 'MV Tasman Pioneer',
    vesselId: 'VESSEL-003',
    checklistId: 'INS-04',
    checklistItemTitle: 'Cargo Ship Safety Equipment',
    title: 'Recalibrate bridge EPIRB hydrostatic release mechanism',
    findingDescription: 'EPIRB battery expiry date approaching within 60 days.',
    owner: 'Northwind Marine Technical Dept',
    dueDate: '15 Oct 2026',
    status: 'Open',
    inspectorNotes: 'Noted during pre-charter verification audit.',
    createdDate: '18 Sep 2026',
    evidences: [
      {
        id: 'EV-122',
        title: 'Bridge EPIRB serial & battery inspection photo',
        type: 'Photo',
        fileName: 'bridge_epirb_tag.jpg',
        fileSize: '2.1 MB',
        uploadedAt: '18 Sep 2026 13:50',
        uploadedBy: 'Inspector Marcus Vance',
      },
    ],
  },
  {
    id: 'CAPA-123',
    vesselName: 'MV Kimberley Guardian',
    vesselId: 'VESSEL-006',
    checklistId: 'INS-01',
    checklistItemTitle: 'ERRV Rescue Craft Davit System',
    title: 'Inspect starboard fast rescue craft (FRC) winch brake lining',
    findingDescription: 'FRC winch brake friction pad wear measured near maintenance threshold.',
    owner: 'Northwind Marine Technical Dept',
    dueDate: '20 Oct 2026',
    status: 'Open',
    inspectorNotes: 'Logged during annual safety standby audit.',
    createdDate: '20 Sep 2026',
    evidences: [
      {
        id: 'EV-123',
        title: 'FRC davit winch brake measurement report',
        type: 'Document',
        fileName: 'frc_winch_measurement_log.pdf',
        fileSize: '780 KB',
        uploadedAt: '20 Sep 2026 14:10',
        uploadedBy: 'Inspector Marcus Vance',
      },
    ],
  },
  {
    id: 'CAPA-124',
    vesselName: 'MV Ningaloo Voyager',
    vesselId: 'VESSEL-007',
    checklistId: 'INS-06',
    checklistItemTitle: 'MARPOL Annex IV · Sewage Treatment Plant',
    title: 'Replace aeration blower filter on sewage treatment unit',
    findingDescription: 'Sewage plant blower inlet filter clogged, causing mild pressure drop.',
    owner: 'Northwind Marine Technical Dept',
    dueDate: '28 Oct 2026',
    status: 'Open',
    inspectorNotes: 'Class surveyor requested replacement prior to next charter departure.',
    createdDate: '21 Sep 2026',
    evidences: [
      {
        id: 'EV-124',
        title: 'Sewage plant blower inlet photo',
        type: 'Photo',
        fileName: 'sewage_blower_filter.jpg',
        fileSize: '1.9 MB',
        uploadedAt: '21 Sep 2026 11:45',
        uploadedBy: 'Inspector Marcus Vance',
      },
    ],
  },
];
