/* 
  file summary: realistic maritime-accurate mock datasets for vessels, assurance sets, Document Library, and audit trail events.
  responsibilities: populates initial state with 3 OSV vessels across all 11 particulars categories, 3 assurance sets, 8 statutory/crew documents, and immutable audit logs.
  role in system: loaded by Zustand store (useMapStore.ts) on initialization.
*/

import { Vessel } from '../types/vessel';
import { AssuranceSet } from '../types/assurance';
import { MasterDocument } from '../types/document';
import { AuditTrailEvent } from '../types/audit';

export const MOCK_VESSELS: Vessel[] = [
  {
    id: 'VESSEL-001',
    name: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    officialRegNumber: 'OSV-44-2019',
    mmsiNumber: '503728940',
    callSign: 'VJQ4821',
    flagState: 'Australia',
    portOfRegistry: 'Fremantle, WA',
    status: 'Under Charter',
    complianceReadinessScore: 94,
    vesselType: 'Offshore Support Vessel (OSV)',
    vesselSubtype: 'AHTS / PSV',
    intendedUse: 'Offshore Supply & Towing',
    tradingArea: 'International',
    classificationSociety: 'DNV',
    classNotation: '+100A1 Offshore Supply Vessel (AHTS/PSV) DP2',
    hullType: 'Double Bottom / Double Side Steel',
    ispsSolasStatus: 'Fully Certified SOLAS/ISPS',
    yearBuilt: 2019,
    shipyardBuilder: 'Damen Shipyards Group',
    lengthOverallMeters: 83.4,
    beamMeters: 18.0,
    draftMeters: 5.8,
    grossTonnageGT: 3250,
    deadweightTonnageDWT: 4100,
    dynamicPositioningClass: 'DP2 (Kongsberg K-Pos)',
    mainEnginePowerKW: '2x 2400 kW Wärtsilä 6L26',
    registeredOwner: 'Pacific Ocean Logistics Operations Pty Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 894 123 765',
    ismCompany: 'Ocean Fleet Management Services Ltd',
    technicalManager: 'Pacific Ship Management Ltd',
    docNumber: 'DOC-DNV-2024-88',
    contact247: '+61 8 9234 5678 (24/7 Ops Center)',
    statutoryCertificates: [
      {
        id: 'SC-01',
        name: 'Certificate of Class',
        certificateNumber: 'DNV-STAT-2026-99',
        issuingBody: 'DNV',
        issueDate: '2024-01-15',
        expiryDate: '2029-01-14',
        status: 'Valid',
      },
      {
        id: 'SC-02',
        name: 'Cargo Ship Safety Equipment',
        certificateNumber: 'DNV-SE-9042',
        issuingBody: 'DNV',
        issueDate: '2023-06-10',
        expiryDate: '2026-11-30',
        status: 'Expiring Soon',
      },
      {
        id: 'SC-03',
        name: 'International Oil Pollution Prevention (IOPP)',
        certificateNumber: 'AMSA-IOPP-4481',
        issuingBody: 'AMSA',
        issueDate: '2022-04-01',
        expiryDate: '2027-04-01',
        status: 'Valid',
      },
    ],
    hmInsurer: 'Standard Club Marine Underwriters',
    piClubName: 'Gard P&I Club Norway',
    policyNumber: 'PI-2026-88492',
    policyExpiryDate: '2027-02-20',
    safeManningComplement: 14,
    certifiedOfficersRatings: '6 Officers / 8 Ratings',
    masterName: 'Capt. James Stirling',
    lifeboatCapacity: 30,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Alfa Laval PureBallast 3.2 (USCG Approved)',
    owCalibrationDate: '2026-01-10',
    masterCertificateUploadCount: 14,
    clientHistory: [
      {
        id: 'CH-001',
        clientOrganization: 'Chevron Australia Pty Ltd',
        charterTitle: 'Chevron Gorgon Offshore Support Charter',
        assuranceSetId: 'AS-2026-001',
        charterStart: '2025-03-01',
        charterEnd: '2026-02-28',
        outcome: 'Completed',
        notes: 'Charter completed with full statutory compliance sign-off.',
      },
      {
        id: 'CH-002',
        clientOrganization: 'Woodside Energy Ltd',
        charterTitle: 'North West Shelf PSV Campaign',
        assuranceSetId: 'AS-2025-088',
        charterStart: '2024-06-15',
        charterEnd: '2025-05-30',
        outcome: 'Approved',
        notes: 'Renewed class and safety certificates prior to charter window.',
      },
      {
        id: 'CH-003',
        clientOrganization: 'Chevron Australia Pty Ltd',
        charterTitle: 'Chevron Gorgon Charter Vetting (Current)',
        assuranceSetId: 'AS-2026-001',
        charterStart: '2026-11-01',
        charterEnd: '2027-11-01',
        outcome: 'In Progress',
        notes: 'Active assurance set — verification stage.',
      },
    ],
  },
  {
    id: 'VESSEL-002',
    name: 'MV Coral Titan',
    imoNumber: '9284710',
    officialRegNumber: 'OSV-88-2021',
    mmsiNumber: '503912049',
    callSign: 'VJQ9912',
    flagState: 'Australia',
    portOfRegistry: 'Dampier, WA',
    status: 'In Operations',
    complianceReadinessScore: 88,
    vesselType: 'Offshore Support Vessel (OSV)',
    vesselSubtype: 'AHTS',
    intendedUse: 'Anchor Handling & Supply',
    tradingArea: 'International',
    classificationSociety: "Lloyd's Register",
    classNotation: '+100A1 Multi-Role Anchor Handling Tug Supply',
    hullType: 'Double Hull Reinforced Steel',
    ispsSolasStatus: 'Certified SOLAS/ISPS',
    yearBuilt: 2021,
    shipyardBuilder: 'Vard Group AS',
    lengthOverallMeters: 92.0,
    beamMeters: 21.0,
    draftMeters: 6.5,
    grossTonnageGT: 4500,
    deadweightTonnageDWT: 5200,
    dynamicPositioningClass: 'DP3 (Kongsberg K-Pos)',
    mainEnginePowerKW: '4x 3000 kW Rolls-Royce Bergen',
    registeredOwner: 'Coral Marine Assets Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 771 902 441',
    ismCompany: 'Titan Fleet Services Ltd',
    technicalManager: 'Titan Fleet Services Ltd',
    docNumber: 'DOC-LR-2025-11',
    contact247: '+61 8 9144 1122',
    statutoryCertificates: [
      {
        id: 'SC-04',
        name: 'Certificate of Class',
        certificateNumber: 'LR-CLASS-88301',
        issuingBody: "Lloyd's Register",
        issueDate: '2024-03-01',
        expiryDate: '2029-03-01',
        status: 'Valid',
      },
    ],
    hmInsurer: 'Allianz Marine & Transit',
    piClubName: 'Britannia P&I Club',
    policyNumber: 'BRIT-99201',
    policyExpiryDate: '2027-05-15',
    safeManningComplement: 16,
    certifiedOfficersRatings: '7 Officers / 9 Ratings',
    masterName: 'Capt. Sarah Jenkins',
    lifeboatCapacity: 36,
    fuelType: 'Dual Fuel LNG / MGO',
    lowSulphurCompliant: true,
    bwtsSpec: 'Wärtsilä Aquarius UV',
    owCalibrationDate: '2025-11-20',
    masterCertificateUploadCount: 12,
    clientHistory: [
      {
        id: 'CH-010',
        clientOrganization: 'Shell Australia Pty Ltd',
        charterTitle: 'Shell Prelude Annual Audit',
        assuranceSetId: 'AS-2026-002',
        charterStart: '2026-10-15',
        charterEnd: '2027-04-15',
        outcome: 'In Progress',
        notes: 'Provider-initiated assurance — validation stage.',
      },
      {
        id: 'CH-011',
        clientOrganization: 'BHP Petroleum',
        charterTitle: 'Scarborough Field Supply Run',
        charterStart: '2023-09-01',
        charterEnd: '2024-08-31',
        outcome: 'Completed',
        notes: 'Successful charter with zero compliance exceptions.',
      },
    ],
  },
  {
    id: 'VESSEL-003',
    name: 'MV Tasman Pioneer',
    imoNumber: '9648102',
    officialRegNumber: 'OSV-12-2018',
    mmsiNumber: '503118492',
    callSign: 'VJQ1044',
    flagState: 'Australia',
    portOfRegistry: 'Darwin, NT',
    status: 'In Transit',
    complianceReadinessScore: 72,
    vesselType: 'Offshore Support Vessel (OSV)',
    vesselSubtype: 'PSV',
    intendedUse: 'Platform Supply',
    tradingArea: 'Domestic / Coastal',
    classificationSociety: 'ABS',
    classNotation: '+A1 Offshore Support Vessel (PSV) Fire Fighting Class 1',
    hullType: 'Double Bottom Steel',
    ispsSolasStatus: 'Certified SOLAS/ISPS',
    yearBuilt: 2018,
    shipyardBuilder: 'Keppel Offshore & Marine',
    lengthOverallMeters: 78.5,
    beamMeters: 17.2,
    draftMeters: 5.4,
    grossTonnageGT: 2900,
    deadweightTonnageDWT: 3600,
    dynamicPositioningClass: 'DP2 (Converteam)',
    mainEnginePowerKW: '2x 2200 kW Caterpillar',
    registeredOwner: 'Tasman Maritime Operations Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 661 004 881',
    ismCompany: 'Tasman Maritime Operations Ltd',
    technicalManager: 'Tasman Maritime Operations Ltd',
    docNumber: 'DOC-ABS-2023-45',
    contact247: '+61 8 8941 0022',
    statutoryCertificates: [
      {
        id: 'SC-05',
        name: 'Certificate of Class',
        certificateNumber: 'ABS-STAT-7721',
        issuingBody: 'ABS',
        issueDate: '2023-02-10',
        expiryDate: '2028-02-10',
        status: 'Valid',
      },
      {
        id: 'SC-06',
        name: 'Cargo Ship Safety Equipment',
        certificateNumber: 'ABS-SE-3310',
        issuingBody: 'ABS',
        issueDate: '2024-01-05',
        expiryDate: '2026-10-15',
        status: 'Expiring Soon',
      },
    ],
    hmInsurer: 'QBE Marine Insurance',
    piClubName: 'UK P&I Club',
    policyNumber: 'UKPI-448102',
    policyExpiryDate: '2026-10-31',
    safeManningComplement: 12,
    certifiedOfficersRatings: '5 Officers / 7 Ratings',
    masterName: 'Capt. Marcus Vance',
    lifeboatCapacity: 28,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Desmi Ocean Guard Compact Clean',
    owCalibrationDate: '2025-08-14',
    masterCertificateUploadCount: 10,
    clientHistory: [
      {
        id: 'CH-020',
        clientOrganization: 'Inpex Operations Australia',
        charterTitle: 'Ichthys Field PSV Support',
        assuranceSetId: 'AS-2026-003',
        charterStart: '2026-04-01',
        charterEnd: '2026-12-31',
        outcome: 'In Progress',
        notes: 'Awaiting safety equipment certificate renewal.',
      },
      {
        id: 'CH-021',
        clientOrganization: 'Santos Ltd',
        charterTitle: 'Bayu-Undan Supply Campaign',
        charterStart: '2022-01-10',
        charterEnd: '2022-11-20',
        outcome: 'Rejected',
        notes: 'Assurance rejected — expired IOPP certificate at charter commencement.',
      },
    ],
  },
  {
    id: 'VESSEL-004',
    name: 'MV Southern Cross',
    imoNumber: '9438102',
    officialRegNumber: 'SSV-99-2022',
    mmsiNumber: '503881029',
    callSign: 'VJQ8822',
    flagState: 'Australia',
    portOfRegistry: 'Fremantle, WA',
    status: 'Under Charter',
    complianceReadinessScore: 96,
    vesselType: 'Subsea Support Vessel (SSV)',
    vesselSubtype: 'ROV Support & Construction',
    intendedUse: 'Subsea Inspection & Intervention',
    tradingArea: 'International',
    classificationSociety: 'DNV',
    classNotation: '+100A1 Subsea Support Vessel DP3 ROV',
    hullType: 'Double Hull Heavy Steel',
    ispsSolasStatus: 'Fully Certified SOLAS/ISPS',
    yearBuilt: 2022,
    shipyardBuilder: 'Vard Group AS',
    lengthOverallMeters: 98.4,
    beamMeters: 22.0,
    draftMeters: 6.8,
    grossTonnageGT: 5800,
    deadweightTonnageDWT: 6200,
    dynamicPositioningClass: 'DP3 (Kongsberg K-Pos)',
    mainEnginePowerKW: '4x 3200 kW Wärtsilä 8L32',
    registeredOwner: 'Offshore Subsea Logistics Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 912 334 102',
    ismCompany: 'Offshore Subsea Logistics Ltd',
    technicalManager: 'Offshore Subsea Logistics Ltd',
    docNumber: 'DOC-DNV-2025-401',
    contact247: '+61 8 9482 9900',
    statutoryCertificates: [
      {
        id: 'SC-07',
        name: 'Certificate of Class',
        certificateNumber: 'DNV-STAT-2026-401',
        issuingBody: 'DNV',
        issueDate: '2024-05-10',
        expiryDate: '2029-05-09',
        status: 'Valid',
      },
      {
        id: 'SC-08',
        name: 'Cargo Ship Safety Construction',
        certificateNumber: 'DNV-SC-8812',
        issuingBody: 'DNV',
        issueDate: '2024-01-12',
        expiryDate: '2028-12-31',
        status: 'Valid',
      },
    ],
    hmInsurer: 'Gard P&I Club Norway',
    piClubName: 'Gard P&I Club Norway',
    policyNumber: 'PI-2026-99104',
    policyExpiryDate: '2027-04-30',
    safeManningComplement: 20,
    certifiedOfficersRatings: '8 Officers / 12 Ratings',
    masterName: 'Capt. David Vance',
    lifeboatCapacity: 45,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Alfa Laval PureBallast 3.2',
    owCalibrationDate: '2026-02-15',
    masterCertificateUploadCount: 16,
    clientHistory: [
      {
        id: 'CH-030',
        clientOrganization: 'Woodside Energy Ltd',
        charterTitle: 'Woodside Scarborough Subsea Charter',
        assuranceSetId: 'AS-2026-004',
        charterStart: '2026-10-01',
        charterEnd: '2027-10-01',
        outcome: 'In Progress',
        notes: 'Charter assurance in progress — verification stage.',
      },
    ],
  },
  {
    id: 'VESSEL-005',
    name: 'MV Atlantic Ocean',
    imoNumber: '9712044',
    officialRegNumber: 'AHTS-44-2020',
    mmsiNumber: '503448102',
    callSign: 'VJQ5544',
    flagState: 'Australia',
    portOfRegistry: 'Karratha, WA',
    status: 'Under Charter',
    complianceReadinessScore: 91,
    vesselType: 'Offshore Support Vessel (OSV)',
    vesselSubtype: 'AHTS / Towing',
    intendedUse: 'Offshore Rig Towing & Supply',
    tradingArea: 'International',
    classificationSociety: 'ABS',
    classNotation: '+A1 Offshore Support Vessel DP2 Towing',
    hullType: 'Double Bottom Steel',
    ispsSolasStatus: 'Certified SOLAS/ISPS',
    yearBuilt: 2020,
    shipyardBuilder: 'Keppel FELS Shipyard',
    lengthOverallMeters: 85.0,
    beamMeters: 19.5,
    draftMeters: 6.0,
    grossTonnageGT: 3800,
    deadweightTonnageDWT: 4400,
    dynamicPositioningClass: 'DP2 (Kongsberg)',
    mainEnginePowerKW: '2x 2800 kW Caterpillar C280',
    registeredOwner: 'Northwind Marine Pty Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 552 109 841',
    ismCompany: 'Northwind Marine Pty Ltd',
    technicalManager: 'Northwind Marine Pty Ltd',
    docNumber: 'DOC-ABS-2025-104',
    contact247: '+61 8 9185 2200',
    statutoryCertificates: [
      {
        id: 'SC-09',
        name: 'Certificate of Class',
        certificateNumber: 'ABS-CLASS-99201',
        issuingBody: 'ABS',
        issueDate: '2023-09-01',
        expiryDate: '2028-09-01',
        status: 'Valid',
      },
    ],
    hmInsurer: 'Standard Club Marine Underwriters',
    piClubName: 'Standard Club P&I',
    policyNumber: 'STD-PI-88204',
    policyExpiryDate: '2027-03-31',
    safeManningComplement: 15,
    certifiedOfficersRatings: '6 Officers / 9 Ratings',
    masterName: 'Capt. Liam O’Connor',
    lifeboatCapacity: 32,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Wärtsilä Aquarius UV',
    owCalibrationDate: '2026-01-20',
    masterCertificateUploadCount: 14,
    clientHistory: [
      {
        id: 'CH-040',
        clientOrganization: 'Southern Basin Energy Pty Ltd',
        charterTitle: 'Southern Basin Platform Support Charter',
        assuranceSetId: 'AS-2026-005',
        charterStart: '2026-09-15',
        charterEnd: '2027-09-15',
        outcome: 'In Progress',
        notes: 'Charterer approval stage.',
      },
    ],
  },
  {
    id: 'VESSEL-006',
    name: 'MV Kimberley Guardian',
    imoNumber: '9823109',
    officialRegNumber: 'ERRV-11-2021',
    mmsiNumber: '503102948',
    callSign: 'VJQ7711',
    flagState: 'Australia',
    portOfRegistry: 'Broome, WA',
    status: 'In Operations',
    complianceReadinessScore: 84,
    vesselType: 'Emergency Response & Rescue Vessel (ERRV)',
    vesselSubtype: 'ERRV / Standby Safety',
    intendedUse: 'Offshore Rescue & Standby',
    tradingArea: 'Domestic / Coastal',
    classificationSociety: 'Bureau Veritas',
    classNotation: 'BV +100A1 ERRV Rescue Class 1 DP2',
    hullType: 'Double Bottom Steel',
    ispsSolasStatus: 'Certified SOLAS/ISPS',
    yearBuilt: 2021,
    shipyardBuilder: 'Austal Ships Australia',
    lengthOverallMeters: 74.0,
    beamMeters: 16.5,
    draftMeters: 5.2,
    grossTonnageGT: 2600,
    deadweightTonnageDWT: 3100,
    dynamicPositioningClass: 'DP2 (Kongsberg K-Pos)',
    mainEnginePowerKW: '2x 2000 kW MTU 16V4000',
    registeredOwner: 'Kimberley Marine Services Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 441 902 118',
    ismCompany: 'Kimberley Marine Services Ltd',
    technicalManager: 'Kimberley Marine Services Ltd',
    docNumber: 'DOC-BV-2024-88',
    contact247: '+61 8 9192 4400',
    statutoryCertificates: [
      {
        id: 'SC-10',
        name: 'Certificate of Class',
        certificateNumber: 'BV-CLASS-44912',
        issuingBody: 'Bureau Veritas',
        issueDate: '2024-02-01',
        expiryDate: '2029-02-01',
        status: 'Valid',
      },
    ],
    hmInsurer: 'QBE Marine Insurance',
    piClubName: 'North of England P&I',
    policyNumber: 'NEPI-55102',
    policyExpiryDate: '2027-01-31',
    safeManningComplement: 14,
    certifiedOfficersRatings: '6 Officers / 8 Ratings',
    masterName: 'Capt. Andrew Ross',
    lifeboatCapacity: 60,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Desmi Ocean Guard',
    owCalibrationDate: '2025-10-10',
    masterCertificateUploadCount: 11,
    clientHistory: [
      {
        id: 'CH-050',
        clientOrganization: 'Santos Australia Pty Ltd',
        charterTitle: 'Santos Carnarvon Basin ERRV Charter',
        assuranceSetId: 'AS-2026-006',
        charterStart: '2026-11-15',
        charterEnd: '2027-05-15',
        outcome: 'In Progress',
        notes: 'Validation stage.',
      },
    ],
  },
  {
    id: 'VESSEL-007',
    name: 'MV Ningaloo Voyager',
    imoNumber: '9910482',
    officialRegNumber: 'PSV-77-2023',
    mmsiNumber: '503991024',
    callSign: 'VJQ3388',
    flagState: 'Australia',
    portOfRegistry: 'Exmouth, WA',
    status: 'Port Stay',
    complianceReadinessScore: 79,
    vesselType: 'Offshore Support Vessel (OSV)',
    vesselSubtype: 'PSV / Deck Supply',
    intendedUse: 'Platform Deck Supply & Liquid Mud',
    tradingArea: 'Domestic / Coastal',
    classificationSociety: "Lloyd's Register",
    classNotation: '+100A1 Offshore Support Vessel (PSV) DP2',
    hullType: 'Double Bottom Steel',
    ispsSolasStatus: 'Certified SOLAS/ISPS',
    yearBuilt: 2023,
    shipyardBuilder: 'Damen Shipyards',
    lengthOverallMeters: 80.0,
    beamMeters: 17.8,
    draftMeters: 5.6,
    grossTonnageGT: 3100,
    deadweightTonnageDWT: 3800,
    dynamicPositioningClass: 'DP2 (Converteam)',
    mainEnginePowerKW: '2x 2300 kW Wärtsilä',
    registeredOwner: 'Ningaloo Offshore Supply Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 881 204 991',
    ismCompany: 'Ningaloo Offshore Supply Ltd',
    technicalManager: 'Ningaloo Offshore Supply Ltd',
    docNumber: 'DOC-LR-2025-88',
    contact247: '+61 8 9949 1100',
    statutoryCertificates: [
      {
        id: 'SC-11',
        name: 'Certificate of Class',
        certificateNumber: 'LR-CLASS-99104',
        issuingBody: "Lloyd's Register",
        issueDate: '2023-11-01',
        expiryDate: '2028-11-01',
        status: 'Valid',
      },
    ],
    hmInsurer: 'Allianz Marine',
    piClubName: 'Britannia P&I',
    policyNumber: 'BRIT-44910',
    policyExpiryDate: '2026-11-30',
    safeManningComplement: 12,
    certifiedOfficersRatings: '5 Officers / 7 Ratings',
    masterName: 'Capt. Thomas Wright',
    lifeboatCapacity: 30,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Alfa Laval PureBallast',
    owCalibrationDate: '2025-12-05',
    masterCertificateUploadCount: 9,
    clientHistory: [
      {
        id: 'CH-060',
        clientOrganization: 'Beach Energy Ltd',
        charterTitle: 'Beach Energy Otway Supply Run',
        assuranceSetId: 'AS-2026-007',
        charterStart: '2026-12-01',
        charterEnd: '2027-06-01',
        outcome: 'In Progress',
        notes: 'Initiated stage.',
      },
    ],
  },
];

export const MOCK_ASSURANCE_SETS: AssuranceSet[] = [
  {
    id: 'AS-2026-001',
    title: 'Chevron Gorgon Charter Vetting',
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Chevron Australia Pty Ltd',
    initiatorRole: 'C Admin · Client Created',
    charterer: 'Chevron Australia Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-11-01',
    stage: 'Approval',
    readinessScore: 94,
    mandatoryInspectionRequired: true,
    inspectionCompleted: true,
    assignedSubmitter: 'M. Chen (Pacific Ocean Logistics Operations)',
    assignedVerifier: 'A. Fontaine (DNV Compliance Services)',
    assignedInspector: 'N. Technical (AMSA Marine Audit Division)',
    assignedApprover: 'P. Nardelli (Chevron Australia Pty Ltd)',
    requirements: [
      {
        id: 'REQ-101',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 98,
        documentId: 'DOC-2026-001',
        verifierStatus: 'Verified',
        notes: 'DNV Certificate verified against class registry database.',
        linkedDocumentId: ''
      },
      {
        id: 'REQ-102',
        category: 'Statutory Certificate',
        title: 'Cargo Ship Safety Equipment',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 96,
        documentId: 'DOC-2026-002',
        verifierStatus: 'Verified',
        notes: 'Safety equipment annual survey completed.',
        linkedDocumentId: ''
      },
      {
        id: 'REQ-103',
        category: 'Crew Credential',
        title: 'STCW Master CoC Endorsement',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 99,
        documentId: 'DOC-2026-004',
        verifierStatus: 'Verified',
        notes: 'AMSA Master Unlimited endorsement verified.',
        linkedDocumentId: ''
      },
      {
        id: 'REQ-104',
        category: 'Environmental',
        title: 'IOPP Certificate Annex I',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 92,
        documentId: 'DOC-2026-003',
        verifierStatus: 'Verified',
        notes: 'OWS 15ppm calibration seal photo verified.',
        linkedDocumentId: ''
      },
    ],
    stakeholders: undefined,
    assignedStakeholders: undefined,
    createdByPersona: ''
  },
  {
    id: 'AS-2026-002',
    title: 'Shell Prelude Annual Audit',
    vesselId: 'VESSEL-002',
    vesselName: 'MV Coral Titan',
    imoNumber: '9284710',
    initiatorOrg: 'Coral Marine Assets Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Shell Australia Pty Ltd',
    charterWindowStart: '2026-10-15',
    charterWindowEnd: '2027-04-15',
    stage: 'Validation',
    readinessScore: 88,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    assignedSubmitter: 'S. Taylor (Coral Marine Assets Ltd)',
    assignedVerifier: "R. Thorne (Lloyd's Register Marine)",
    assignedApprover: 'K. Osei (Shell Australia Operations)',
    requirements: [
      {
        id: 'REQ-201',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 97,
        documentId: 'DOC-2026-005',
        verifierStatus: 'Pending',
        linkedDocumentId: ''
      },
    ],
    stakeholders: undefined,
    assignedStakeholders: undefined,
    createdByPersona: ''
  },
  {
    id: 'AS-2026-003',
    title: 'Inpex Ichthys Inspection',
    vesselId: 'VESSEL-003',
    vesselName: 'MV Tasman Pioneer',
    imoNumber: '9648102',
    initiatorOrg: 'Inpex Operations Australia',
    initiatorRole: 'C Admin · Client Created',
    charterer: 'Inpex Operations Australia',
    charterWindowStart: '2026-12-01',
    charterWindowEnd: '2027-06-01',
    stage: 'Initiated',
    readinessScore: 78,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    assignedSubmitter: 'M. Vance (Tasman Maritime Operations Ltd)',
    assignedVerifier: 'L. Vance (ABS Maritime Inspectorate)',
    assignedInspector: 'G. Harrison (Marine Inspection Bureau)',
    assignedApprover: 'H. Miller (Inpex Operations Australia)',
    requirements: [
      {
        id: 'REQ-301',
        category: 'Statutory Certificate',
        title: 'Certificate of Registry',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 95,
        documentId: 'DOC-2026-006',
        verifierStatus: 'Pending',
        linkedDocumentId: ''
      },
    ],
    stakeholders: undefined,
    assignedStakeholders: undefined,
    createdByPersona: ''
  },
  {
    id: 'AS-2026-004',
    title: 'Woodside Scarborough Subsea Charter',
    vesselId: 'VESSEL-004',
    vesselName: 'MV Southern Cross',
    imoNumber: '9438102',
    initiatorOrg: 'Woodside Energy Ltd',
    initiatorRole: 'C Admin · Client Created',
    charterWindowStart: '2026-10-01',
    charterWindowEnd: '2027-10-01',
    stage: 'Verification',
    readinessScore: 96,
    mandatoryInspectionRequired: true,
    inspectionCompleted: true,
    assignedSubmitter: 'R. Davis (Offshore Subsea Logistics)',
    assignedVerifier: 'A. Fontaine (DNV Compliance Services)',
    assignedInspector: 'N. Technical (AMSA Marine Audit Division)',
    assignedApprover: 'H. Miller (Woodside Energy Ltd)',
    requirements: [
      {
        id: 'REQ-401',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 99,
        verifierStatus: 'Verified',
        notes: 'DNV class notation verified for subsea ROV operations.',
        linkedDocumentId: ''
      },
      {
        id: 'REQ-402',
        category: 'Statutory Certificate',
        title: 'Cargo Ship Safety Construction',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 98,
        verifierStatus: 'Verified',
        notes: 'Safety construction certificate valid through 2028.',
        linkedDocumentId: ''
      },
    ],
    stakeholders: undefined,
    assignedStakeholders: undefined,
    createdByPersona: ''
  },
  {
    id: 'AS-2026-005',
    title: 'Southern Basin Platform Support Charter',
    vesselId: 'VESSEL-005',
    vesselName: 'MV Atlantic Ocean',
    imoNumber: '9712044',
    initiatorOrg: 'Southern Basin Energy Pty Ltd',
    initiatorRole: 'C Admin · Client Created',
    charterWindowStart: '2026-09-15',
    charterWindowEnd: '2027-09-15',
    stage: 'Approval',
    readinessScore: 91,
    mandatoryInspectionRequired: true,
    inspectionCompleted: true,
    assignedSubmitter: 'E. Ramirez (Northwind Marine Pty Ltd)',
    assignedVerifier: 'A. Fontaine (DNV Compliance Services)',
    assignedInspector: 'N. Technical (AMSA Marine Audit Division)',
    assignedApprover: 'S. Basin (Southern Basin Energy Pty Ltd)',
    requirements: [
      {
        id: 'REQ-501',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 96,
        verifierStatus: 'Verified',
        notes: 'ABS Class endorsement verified.',
        linkedDocumentId: ''
      },
      {
        id: 'REQ-502',
        category: 'Inspection Report',
        title: 'Visual Vessel Inspection & Safety Audit',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 95,
        verifierStatus: 'Verified',
        notes: 'Physical survey completed with 1 deficiency logged for liferaft HRU.',
        linkedDocumentId: ''
      },
    ],
    stakeholders: undefined,
    assignedStakeholders: undefined,
    createdByPersona: ''
  },
  {
    id: 'AS-2026-006',
    title: 'Santos Carnarvon Basin ERRV Charter',
    vesselId: 'VESSEL-006',
    vesselName: 'MV Kimberley Guardian',
    imoNumber: '9823109',
    initiatorOrg: 'Kimberley Marine Services Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterWindowStart: '2026-11-15',
    charterWindowEnd: '2027-05-15',
    stage: 'Validation',
    readinessScore: 84,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    assignedSubmitter: 'K. Hughes (Kimberley Marine Services)',
    assignedVerifier: 'P. Dawson (BV Compliance)',
    assignedInspector: 'G. Harrison (Marine Inspection Bureau)',
    assignedApprover: 'J. Vance (Santos Australia)',
    requirements: [
      {
        id: 'REQ-601',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 94,
        verifierStatus: 'Pending',
        linkedDocumentId: ''
      },
    ],
    stakeholders: undefined,
    assignedStakeholders: undefined,
    createdByPersona: ''
  },
  {
    id: 'AS-2026-007',
    title: 'Beach Energy Otway Supply Run',
    vesselId: 'VESSEL-007',
    vesselName: 'MV Ningaloo Voyager',
    imoNumber: '9910482',
    initiatorOrg: 'Ningaloo Offshore Supply Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterWindowStart: '2026-12-01',
    charterWindowEnd: '2027-06-01',
    stage: 'Initiated',
    readinessScore: 79,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    assignedSubmitter: 'T. Wright (Ningaloo Offshore Supply)',
    assignedVerifier: 'R. Thorne (Lloyds Register)',
    assignedInspector: 'G. Harrison (Marine Inspection Bureau)',
    assignedApprover: 'B. Cooper (Beach Energy)',
    requirements: [
      {
        id: 'REQ-701',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 92,
        verifierStatus: 'Pending',
        linkedDocumentId: ''
      },
    ],
    stakeholders: undefined,
    assignedStakeholders: undefined,
    createdByPersona: ''
  },
];

export const MOCK_DOCUMENTS: MasterDocument[] = [
  {
    id: 'DOC-2026-099',
    title: 'Certificate of Class',
    entityType: 'Vessel Certificate',
    vesselId: '',
    certificateNo: 'DNV-STAT-2026-8810',
    issuingAuthority: 'DNV',
    expiryDate: '2029-08-31',
    ocrConfidence: 99.4,
    complianceState: 'Valid',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-09-15T11:20:00Z',
        uploadedBy: 'Document Vault Submitter',
        fileSizeBytes: 2300000,
        fileName: 'DNV_Class_Cert_MV_Pacific_Pioneer.pdf',
        changeSummary: 'Uploaded standalone statutory document in Document Library.',
      },
    ],
    vesselAttributes: {
      title: 'Certificate of Class',
      certificateNumber: 'DNV-STAT-2026-8810',
      certType: 'Statutory Class Certificate',
      issuingBody: 'DNV',
      issueDate: '2024-02-01',
      expiryDate: '2029-08-31',
      vesselName: 'MV Pacific Pioneer',
      imoNumber: '9481902',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2025-08-01',
      ocrConfidence: 99.4,
      status: 'Valid',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Verified',
  },
  {
    id: 'DOC-2026-001',
    title: 'Certificate of Class',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'DNV-STAT-2026-99',
    issuingAuthority: 'DNV',
    expiryDate: '2029-01-14',
    ocrConfidence: 98,
    complianceState: 'Valid',
    currentVersion: 'v1.1',
    versions: [
      {
        versionLabel: 'v1.1',
        uploadedAt: '2026-09-10T08:30:00Z',
        uploadedBy: 'Ops Admin (Submitter)',
        fileSizeBytes: 2450000,
        fileName: 'DNV_Class_Cert_MV_Pacific_Endeavour_v1.1.pdf',
        changeSummary: 'Re-uploaded high resolution scan following verifier request.',
      },
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-08-01T14:15:00Z',
        uploadedBy: 'Ops Admin (Submitter)',
        fileSizeBytes: 2100000,
        fileName: 'DNV_Class_Cert_MV_Pacific_Endeavour_v1.0.pdf',
        changeSummary: 'Initial document upload.',
      },
    ],
    vesselAttributes: {
      title: 'Certificate of Class',
      certificateNumber: 'DNV-STAT-2026-99',
      certType: 'Class Certificate (AHTS/PSV)',
      issuingBody: 'DNV',
      issueDate: '2024-01-15',
      expiryDate: '2029-01-14',
      vesselName: 'MV Pacific Endeavour',
      imoNumber: '9123456',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2026-01-12',
      ocrConfidence: 98,
      status: 'Valid',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Verified',
    verificationNotes: 'Class society confirmed active in IACS register.',
  },
  {
    id: 'DOC-2026-002',
    title: 'Cargo Ship Safety Equipment Certificate',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'DNV-SE-9042',
    issuingAuthority: 'DNV',
    expiryDate: '2026-11-30',
    ocrConfidence: 96,
    complianceState: 'Expiring < 6 Mos',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-07-20T10:00:00Z',
        uploadedBy: 'Submitter Ops',
        fileSizeBytes: 1850000,
        fileName: 'Safety_Equipment_Cert_9042.pdf',
        changeSummary: 'Initial statutory upload.',
      },
    ],
    vesselAttributes: {
      title: 'Cargo Ship Safety Equipment Certificate',
      certificateNumber: 'DNV-SE-9042',
      certType: 'Safety Equipment',
      issuingBody: 'DNV',
      issueDate: '2023-06-10',
      expiryDate: '2026-11-30',
      vesselName: 'MV Pacific Endeavour',
      imoNumber: '9123456',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2025-06-08',
      ocrConfidence: 96,
      status: 'Expiring < 6 Mos',
    },
    validationRules: {
      charterBufferPassed: false, // Expiring within charter window!
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: false,
      exceptionDetails: '6-Month Charter Buffer Breach: Certificate expires before 2027-11-01 charter completion date.',
    },
    verificationStatus: 'Verified',
    verificationNotes: 'Verified with note: renewal survey required prior to charter extension.',
  },
  {
    id: 'DOC-2026-003',
    title: 'International Oil Pollution Prevention (IOPP)',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'AMSA-IOPP-4481',
    issuingAuthority: 'AMSA',
    expiryDate: '2027-04-01',
    ocrConfidence: 92,
    complianceState: 'Mismatch/Exception',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-08-15T11:20:00Z',
        uploadedBy: 'Submitter Ops',
        fileSizeBytes: 1400000,
        fileName: 'AMSA_IOPP_4481.pdf',
        changeSummary: 'Initial statutory upload.',
      },
    ],
    vesselAttributes: {
      title: 'International Oil Pollution Prevention (IOPP)',
      certificateNumber: 'AMSA-IOPP-4481',
      certType: 'MARPOL Annex I',
      issuingBody: 'AMSA',
      issueDate: '2022-04-01',
      expiryDate: '2027-04-01',
      vesselName: 'MV Pacific Endeavour',
      imoNumber: '9123456',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2025-04-01',
      ocrConfidence: 92,
      status: 'Mismatch/Exception',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: false,
      exceptionDetails: 'OWS 15ppm calibration tag photo scan blurred.',
    },
    verificationStatus: 'Correction Requested',
    verificationNotes: 'Please upload clean high-res photo of OWS calibration certificate tag.',
  },
  {
    id: 'DOC-2026-004',
    title: 'STCW Master Unlimited CoC',
    entityType: 'Crew Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'AMSA-STCW-88391',
    issuingAuthority: 'AMSA',
    expiryDate: '2028-09-30',
    ocrConfidence: 99,
    complianceState: 'Valid',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-09-01T09:00:00Z',
        uploadedBy: 'Crewing Administrator',
        fileSizeBytes: 980000,
        fileName: 'Master_CoC_James_Stirling.pdf',
        changeSummary: 'Initial crew credential upload.',
      },
    ],
    crewAttributes: {
      crewName: 'Capt. James Stirling',
      passportId: 'PA-983421',
      rank: 'Master Unlimited',
      certType: 'STCW Reg II/2 Master CoC',
      issuingCenter: 'Australian Maritime Safety Authority (AMSA)',
      issueDate: '2023-09-30',
      expiryDate: '2028-09-30',
      assignedVessel: 'MV Pacific Endeavour',
      nationality: 'Australian',
      trainingDate: '2023-08-15',
      ocrConfidence: 99,
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Verified',
    verificationNotes: 'AMSA public portal CoC verification match confirmed.',
  },
  {
    id: 'DOC-2026-005',
    title: 'Certificate of Class',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-002',
    certificateNo: 'LR-CLASS-88301',
    issuingAuthority: "Lloyd's Register",
    expiryDate: '2029-03-01',
    ocrConfidence: 97,
    complianceState: 'Valid',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-08-20T14:00:00Z',
        uploadedBy: 'Provider Admin',
        fileSizeBytes: 3100000,
        fileName: 'LR_Class_Cert_Coral_Titan.pdf',
        changeSummary: 'Document Library upload.',
      },
    ],
    vesselAttributes: {
      title: 'Certificate of Class',
      certificateNumber: 'LR-CLASS-88301',
      certType: 'Class Certificate (AHTS)',
      issuingBody: "Lloyd's Register",
      issueDate: '2024-03-01',
      expiryDate: '2029-03-01',
      vesselName: 'MV Coral Titan',
      imoNumber: '9284710',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2026-02-28',
      ocrConfidence: 97,
      status: 'Valid',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Pending',
  },
  {
    id: 'DOC-2026-006',
    title: 'Certificate of Registry',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-003',
    certificateNo: 'REG-DARWIN-2018-12',
    issuingAuthority: 'Australian Register of Ships',
    expiryDate: '2030-05-31',
    ocrConfidence: 95,
    complianceState: 'Valid',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-09-02T16:45:00Z',
        uploadedBy: 'Submitter Ops',
        fileSizeBytes: 1200000,
        fileName: 'Registry_Cert_Tasman_Pioneer.pdf',
        changeSummary: 'Initial upload.',
      },
    ],
    vesselAttributes: {
      title: 'Certificate of Registry',
      certificateNumber: 'REG-DARWIN-2018-12',
      certType: 'Statutory Registry',
      issuingBody: 'Australian Register of Ships',
      issueDate: '2018-06-01',
      expiryDate: '2030-05-31',
      vesselName: 'MV Tasman Pioneer',
      imoNumber: '9648102',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2023-06-01',
      ocrConfidence: 95,
      status: 'Valid',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Pending',
  },
];

export const MOCK_AUDIT_TRAIL: AuditTrailEvent[] = [
  {
    id: 'AUD-90481',
    timestampUtc: '2026-09-19T08:15:30Z',
    userId: 'USR-ADMIN-01',
    userRole: 'Administrator',
    organization: 'Pacific Ocean Logistics Pty Ltd',
    action: 'Registered Unique Vessel Record',
    targetAsset: 'MV Pacific Endeavour (IMO 9123456)',
    justificationNotes: 'Initial vessel registration across all 11 particulars categories.',
  },
  {
    id: 'AUD-90482',
    timestampUtc: '2026-09-19T09:22:10Z',
    userId: 'USR-CADMIN-02',
    userRole: 'C Admin',
    organization: 'Chevron Australia Pty Ltd',
    action: 'Initiated Assurance Set',
    targetAsset: 'AS-2026-001 (Chevron Gorgon Charter Vetting)',
    justificationNotes: 'Initiated client-driven vetting for upcoming offshore campaign.',
  },
  {
    id: 'AUD-90483',
    timestampUtc: '2026-09-19T10:05:44Z',
    userId: 'USR-SUBMIT-01',
    userRole: 'Submitter',
    organization: 'Pacific Ocean Logistics Pty Ltd',
    action: 'Uploaded Document Revision v1.1',
    targetAsset: 'DOC-2026-001 (Certificate of Class)',
    fieldDelta: {
      fieldName: 'Version',
      oldValue: 'v1.0',
      newValue: 'v1.1',
    },
    documentStatusDelta: {
      documentId: 'DOC-2026-001',
      oldStatus: 'Correction Requested',
      newStatus: 'Pending Verification',
    },
    justificationNotes: 'Re-uploaded high-res scan following verifier feedback.',
  },
  {
    id: 'AUD-90484',
    timestampUtc: '2026-09-19T11:40:12Z',
    userId: 'USR-VERIFY-01',
    userRole: 'Verifier',
    organization: 'DNV Compliance Services',
    action: 'Verified Statutory Certificate',
    targetAsset: 'DOC-2026-001 (Certificate of Class)',
    documentStatusDelta: {
      documentId: 'DOC-2026-001',
      oldStatus: 'Pending Verification',
      newStatus: 'Verified',
    },
    justificationNotes: 'Confirmed 100% identity match and valid IACS registry entry.',
  },
  {
    id: 'AUD-90485',
    timestampUtc: '2026-09-19T14:10:00Z',
    userId: 'USR-INSPEC-01',
    userRole: 'Inspector',
    organization: 'AMSA Marine Audit Division',
    action: 'Completed On-Site Survey Checklist',
    targetAsset: 'AS-2026-001 (MV Pacific Endeavour)',
    justificationNotes: 'LSA and machinery inspection passed with 1 minor CAPA deficiency.',
  },
];

export const MOCK_USERS: import('../types/user').UserProfile[] = [
  {
    id: 'USR-101',
    name: 'K. Osei',
    email: 'k.osei@northwindmarine.com',
    roles: ['Administrator'],
    userType: 'Organization',
    organization: 'Northwind Marine Pty Ltd',
    departmentOrScope: 'IT Systems & System Governance',
    status: 'Active',
    lastActive: '2026-09-20 02:45 UTC',
  },
  {
    id: 'USR-102',
    name: 'M. Chen',
    email: 'm.chen@northwindmarine.com',
    roles: ['Submitter', 'Verifier'],
    userType: 'Organization',
    organization: 'Northwind Marine Pty Ltd',
    departmentOrScope: 'Vessel Operations & Document Submissions',
    status: 'Active',
    lastActive: '2026-09-19 18:30 UTC',
  },
  {
    id: 'USR-103',
    name: 'J. Vance',
    email: 'j.vance@northwindmarine.com',
    roles: ['Submitter'],
    userType: 'Organization',
    organization: 'Northwind Marine Pty Ltd',
    departmentOrScope: 'Fleet Logistics & Operations',
    status: 'Active',
    lastActive: '2026-09-18 11:15 UTC',
  },
  {
    id: 'USR-104',
    name: 'E. Rostova',
    email: 'e.rostova@northwindmarine.com',
    roles: ['Administrator', 'Submitter'],
    userType: 'Organization',
    organization: 'Northwind Marine Pty Ltd',
    departmentOrScope: 'Quality & Regulatory Compliance',
    status: 'Active',
    lastActive: '2026-09-17 09:40 UTC',
  },
  {
    id: 'USR-201',
    name: 'S. Basin',
    email: 's.basin@southernbasin.com.au',
    roles: ['C Admin', 'Approver'],
    userType: 'Third-Party',
    organization: 'Southern Basin Energy',
    departmentOrScope: 'Client / Charterer Management',
    status: 'Active',
    lastActive: '2026-09-19 15:20 UTC',
  },
  {
    id: 'USR-202',
    name: 'A. Fontaine',
    email: 'a.fontaine@bureauveritas.com',
    roles: ['Verifier'],
    userType: 'Third-Party',
    organization: 'Bureau Veritas Inspectorate',
    departmentOrScope: 'Statutory Verification & Audit',
    status: 'Active',
    lastActive: '2026-09-20 01:10 UTC',
  },
  {
    id: 'USR-203',
    name: 'N. Technical',
    email: 'n.technical@meridian-surveyors.com',
    roles: ['Inspector'],
    userType: 'Third-Party',
    organization: 'Meridian Marine Surveyors',
    departmentOrScope: 'On-Site Physical Inspection',
    status: 'Active',
    lastActive: '2026-09-19 16:05 UTC',
  },
  {
    id: 'USR-204',
    name: 'P. Nardelli',
    email: 'p.nardelli@marine-assurance.gov.au',
    roles: ['Approver'],
    userType: 'Third-Party',
    organization: 'Marine Assurance Authority',
    departmentOrScope: 'Executive Vetting & Sign-Off',
    status: 'Active',
    lastActive: '2026-09-19 14:00 UTC',
  },
  {
    id: 'USR-205',
    name: 'D. Harrison',
    email: 'd.harrison@chevron.com',
    roles: ['C Admin'],
    userType: 'Third-Party',
    organization: 'Chevron Australia',
    departmentOrScope: 'Charter Vetting & Commercial Ops',
    status: 'Pending Invitation',
    lastActive: 'Invitation Sent',
    createdBy: 'C Admin',
    invitedBy: 'C Admin',
  },
  {
    id: 'USR-206',
    name: 'L. Sterling',
    email: 'l.sterling@globalmaritime.com',
    roles: ['Inspector', 'Verifier'],
    userType: 'Third-Party',
    organization: 'Global Maritime Audits',
    departmentOrScope: 'Third-Party Survey Inspectorate',
    status: 'Active',
    lastActive: '2026-09-15 08:30 UTC',
  },
];

