/* 
  file summary: realistic maritime-accurate mock datasets for vessels, assurance sets, master document vault, and audit trail events.
  responsibilities: populates initial state with 3 OSV vessels across all 11 particulars categories, 3 assurance sets, 8 statutory/crew documents, and immutable audit logs.
  role in system: loaded by Zustand store (useMapStore.ts) on initialization.
*/

import { VesselParticulars } from '../types/vessel';
import { AssuranceSet } from '../types/assurance';
import { MasterDocument } from '../types/document';
import { AuditTrailEvent } from '../types/audit';

export const MOCK_VESSELS: VesselParticulars[] = [
  {
    id: 'VESSEL-001',
    name: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    officialRegNumber: 'OSV-44-2019',
    mmsiNumber: '503728940',
    callSign: 'VJQ4821',
    flagState: 'Australia',
    portOfRegistry: 'Fremantle, WA',
    status: 'Under Charter',
    complianceReadinessScore: 94,
    classificationSociety: 'DNV',
    classNotation: '+100A1 Offshore Supply Vessel (AHTS/PSV) DP2',
    hullType: 'Double Bottom / Double Side Steel',
    ispsSolasStatus: 'Fully Certified SOLAS/ISPS',
    yearBuilt: 2019,
    shipyardBuilder: 'Damen Shipyards Group',
    lengthOverallMeters: 83.4,
    beamMeters: 18.0,
    draftMeters: 5.8,
    grossTonnageGT: 3250,
    deadweightTonnageDWT: 4100,
    dynamicPositioningClass: 'DP2 (Kongsberg K-Pos)',
    mainEnginePowerKW: '2x 2400 kW Wärtsilä 6L26',
    registeredOwner: 'Pacific Ocean Logistics Operations Pty Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 894 123 765',
    ismCompany: 'Ocean Fleet Management Services Ltd',
    technicalManager: 'Pacific Ship Management Ltd',
    docNumber: 'DOC-DNV-2024-88',
    contact247: '+61 8 9234 5678 (24/7 Ops Center)',
    statutoryCertificates: [
      {
        id: 'SC-01',
        name: 'Certificate of Class',
        certificateNumber: 'DNV-STAT-2026-99',
        issuingBody: 'DNV',
        issueDate: '2024-01-15',
        expiryDate: '2029-01-14',
        status: 'Valid',
      },
      {
        id: 'SC-02',
        name: 'Cargo Ship Safety Equipment',
        certificateNumber: 'DNV-SE-9042',
        issuingBody: 'DNV',
        issueDate: '2023-06-10',
        expiryDate: '2026-11-30',
        status: 'Expiring Soon',
      },
      {
        id: 'SC-03',
        name: 'International Oil Pollution Prevention (IOPP)',
        certificateNumber: 'AMSA-IOPP-4481',
        issuingBody: 'AMSA',
        issueDate: '2022-04-01',
        expiryDate: '2027-04-01',
        status: 'Valid',
      },
    ],
    hmInsurer: 'Standard Club Marine Underwriters',
    piClubName: 'Gard P&I Club Norway',
    policyNumber: 'PI-2026-88492',
    policyExpiryDate: '2027-02-20',
    safeManningComplement: 14,
    certifiedOfficersRatings: '6 Officers / 8 Ratings',
    masterName: 'Capt. James Stirling',
    lifeboatCapacity: 30,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Alfa Laval PureBallast 3.2 (USCG Approved)',
    owCalibrationDate: '2026-01-10',
    masterCertificateUploadCount: 14,
  },
  {
    id: 'VESSEL-002',
    name: 'MV Coral Titan',
    imoNumber: '9284710',
    officialRegNumber: 'OSV-88-2021',
    mmsiNumber: '503912049',
    callSign: 'VJQ9912',
    flagState: 'Australia',
    portOfRegistry: 'Dampier, WA',
    status: 'In Operations',
    complianceReadinessScore: 88,
    classificationSociety: "Lloyd's Register",
    classNotation: '+100A1 Multi-Role Anchor Handling Tug Supply',
    hullType: 'Double Hull Reinforced Steel',
    ispsSolasStatus: 'Certified SOLAS/ISPS',
    yearBuilt: 2021,
    shipyardBuilder: 'Vard Group AS',
    lengthOverallMeters: 92.0,
    beamMeters: 21.0,
    draftMeters: 6.5,
    grossTonnageGT: 4500,
    deadweightTonnageDWT: 5200,
    dynamicPositioningClass: 'DP3 (Kongsberg K-Pos)',
    mainEnginePowerKW: '4x 3000 kW Rolls-Royce Bergen',
    registeredOwner: 'Coral Marine Assets Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 771 902 441',
    ismCompany: 'Titan Fleet Services Ltd',
    technicalManager: 'Titan Fleet Services Ltd',
    docNumber: 'DOC-LR-2025-11',
    contact247: '+61 8 9144 1122',
    statutoryCertificates: [
      {
        id: 'SC-04',
        name: 'Certificate of Class',
        certificateNumber: 'LR-CLASS-88301',
        issuingBody: "Lloyd's Register",
        issueDate: '2024-03-01',
        expiryDate: '2029-03-01',
        status: 'Valid',
      },
    ],
    hmInsurer: 'Allianz Marine & Transit',
    piClubName: 'Britannia P&I Club',
    policyNumber: 'BRIT-99201',
    policyExpiryDate: '2027-05-15',
    safeManningComplement: 16,
    certifiedOfficersRatings: '7 Officers / 9 Ratings',
    masterName: 'Capt. Sarah Jenkins',
    lifeboatCapacity: 36,
    fuelType: 'Dual Fuel LNG / MGO',
    lowSulphurCompliant: true,
    bwtsSpec: 'Wärtsilä Aquarius UV',
    owCalibrationDate: '2025-11-20',
    masterCertificateUploadCount: 12,
  },
  {
    id: 'VESSEL-003',
    name: 'MV Tasman Pioneer',
    imoNumber: '9648102',
    officialRegNumber: 'OSV-12-2018',
    mmsiNumber: '503118492',
    callSign: 'VJQ1044',
    flagState: 'Australia',
    portOfRegistry: 'Darwin, NT',
    status: 'In Transit',
    complianceReadinessScore: 78,
    classificationSociety: 'ABS',
    classNotation: '+A1 Offshore Support Vessel (PSV) Fire Fighting Class 1',
    hullType: 'Double Bottom Steel',
    ispsSolasStatus: 'Certified SOLAS/ISPS',
    yearBuilt: 2018,
    shipyardBuilder: 'Keppel Offshore & Marine',
    lengthOverallMeters: 78.5,
    beamMeters: 17.2,
    draftMeters: 5.4,
    grossTonnageGT: 2900,
    deadweightTonnageDWT: 3600,
    dynamicPositioningClass: 'DP2 (Converteam)',
    mainEnginePowerKW: '2x 2200 kW Caterpillar',
    registeredOwner: 'Tasman Maritime Operations Ltd',
    ownerType: 'Corporate Entity',
    corporateRegistryNo: 'ACN 661 004 881',
    ismCompany: 'Tasman Maritime Operations Ltd',
    technicalManager: 'Tasman Maritime Operations Ltd',
    docNumber: 'DOC-ABS-2023-45',
    contact247: '+61 8 8941 0022',
    statutoryCertificates: [
      {
        id: 'SC-05',
        name: 'Certificate of Class',
        certificateNumber: 'ABS-STAT-7721',
        issuingBody: 'ABS',
        issueDate: '2023-02-10',
        expiryDate: '2028-02-10',
        status: 'Valid',
      },
    ],
    hmInsurer: 'QBE Marine Insurance',
    piClubName: 'UK P&I Club',
    policyNumber: 'UKPI-448102',
    policyExpiryDate: '2026-10-31',
    safeManningComplement: 12,
    certifiedOfficersRatings: '5 Officers / 7 Ratings',
    masterName: 'Capt. Marcus Vance',
    lifeboatCapacity: 28,
    fuelType: 'MGO Low-Sulphur 0.1%',
    lowSulphurCompliant: true,
    bwtsSpec: 'Desmi Ocean Guard Compact Clean',
    owCalibrationDate: '2025-08-14',
    masterCertificateUploadCount: 10,
  },
];

export const MOCK_ASSURANCE_SETS: AssuranceSet[] = [
  {
    id: 'AS-2026-001',
    title: 'Chevron Gorgon Charter Vetting',
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Chevron Australia Pty Ltd',
    initiatorRole: 'C Admin · Client Created',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-11-01',
    stage: 'Verification',
    readinessScore: 94,
    mandatoryInspectionRequired: true,
    inspectionCompleted: true,
    requirements: [
      {
        id: 'REQ-101',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 98,
        documentId: 'DOC-2026-001',
        verifierStatus: 'Verified',
        notes: 'DNV Certificate verified against class registry database.',
      },
      {
        id: 'REQ-102',
        category: 'Statutory Certificate',
        title: 'Cargo Ship Safety Equipment',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 96,
        documentId: 'DOC-2026-002',
        verifierStatus: 'Verified',
        notes: 'Safety equipment annual survey completed.',
      },
      {
        id: 'REQ-103',
        category: 'Crew Credential',
        title: 'STCW Master CoC Endorsement',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 99,
        documentId: 'DOC-2026-004',
        verifierStatus: 'Verified',
        notes: 'AMSA Master Unlimited endorsement verified.',
      },
      {
        id: 'REQ-104',
        category: 'Environmental',
        title: 'IOPP Certificate Annex I',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 92,
        documentId: 'DOC-2026-003',
        verifierStatus: 'Correction Requested',
        notes: 'OWS 15ppm calibration seal photo requires higher resolution.',
      },
    ],
  },
  {
    id: 'AS-2026-002',
    title: 'Shell Prelude Annual Audit',
    vesselId: 'VESSEL-002',
    vesselName: 'MV Coral Titan',
    imoNumber: '9284710',
    initiatorOrg: 'Pacific Ocean Logistics Operations Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterWindowStart: '2026-10-15',
    charterWindowEnd: '2027-04-15',
    stage: 'Validation',
    readinessScore: 88,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-201',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 97,
        documentId: 'DOC-2026-005',
        verifierStatus: 'Pending',
      },
    ],
  },
  {
    id: 'AS-2026-003',
    title: 'Inpex Ichthys Inspection',
    vesselId: 'VESSEL-003',
    vesselName: 'MV Tasman Pioneer',
    imoNumber: '9648102',
    initiatorOrg: 'Inpex Operations Australia',
    initiatorRole: 'C Admin · Client Created',
    charterWindowStart: '2026-12-01',
    charterWindowEnd: '2027-06-01',
    stage: 'Initiated',
    readinessScore: 78,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-301',
        category: 'Statutory Certificate',
        title: 'Certificate of Registry',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 95,
        documentId: 'DOC-2026-006',
        verifierStatus: 'Pending',
      },
    ],
  },
];

export const MOCK_DOCUMENTS: MasterDocument[] = [
  {
    id: 'DOC-2026-001',
    title: 'Certificate of Class',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'DNV-STAT-2026-99',
    issuingAuthority: 'DNV',
    expiryDate: '2029-01-14',
    ocrConfidence: 98,
    complianceState: 'Valid',
    currentVersion: 'v1.1',
    versions: [
      {
        versionLabel: 'v1.1',
        uploadedAt: '2026-09-10T08:30:00Z',
        uploadedBy: 'Ops Admin (Submitter)',
        fileSizeBytes: 2450000,
        fileName: 'DNV_Class_Cert_MV_Pacific_Endeavour_v1.1.pdf',
        changeSummary: 'Re-uploaded high resolution scan following verifier request.',
      },
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-08-01T14:15:00Z',
        uploadedBy: 'Ops Admin (Submitter)',
        fileSizeBytes: 2100000,
        fileName: 'DNV_Class_Cert_MV_Pacific_Endeavour_v1.0.pdf',
        changeSummary: 'Initial document upload.',
      },
    ],
    vesselAttributes: {
      title: 'Certificate of Class',
      certificateNumber: 'DNV-STAT-2026-99',
      certType: 'Class Certificate (AHTS/PSV)',
      issuingBody: 'DNV',
      issueDate: '2024-01-15',
      expiryDate: '2029-01-14',
      vesselName: 'MV Pacific Endeavour',
      imoNumber: '9123456',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2026-01-12',
      ocrConfidence: 98,
      status: 'Valid',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Verified',
    verificationNotes: 'Class society confirmed active in IACS register.',
  },
  {
    id: 'DOC-2026-002',
    title: 'Cargo Ship Safety Equipment Certificate',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'DNV-SE-9042',
    issuingAuthority: 'DNV',
    expiryDate: '2026-11-30',
    ocrConfidence: 96,
    complianceState: 'Expiring < 6 Mos',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-07-20T10:00:00Z',
        uploadedBy: 'Submitter Ops',
        fileSizeBytes: 1850000,
        fileName: 'Safety_Equipment_Cert_9042.pdf',
        changeSummary: 'Initial statutory upload.',
      },
    ],
    vesselAttributes: {
      title: 'Cargo Ship Safety Equipment Certificate',
      certificateNumber: 'DNV-SE-9042',
      certType: 'Safety Equipment',
      issuingBody: 'DNV',
      issueDate: '2023-06-10',
      expiryDate: '2026-11-30',
      vesselName: 'MV Pacific Endeavour',
      imoNumber: '9123456',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2025-06-08',
      ocrConfidence: 96,
      status: 'Expiring < 6 Mos',
    },
    validationRules: {
      charterBufferPassed: false, // Expiring within charter window!
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: false,
      exceptionDetails: '6-Month Charter Buffer Breach: Certificate expires before 2027-11-01 charter completion date.',
    },
    verificationStatus: 'Verified',
    verificationNotes: 'Verified with note: renewal survey required prior to charter extension.',
  },
  {
    id: 'DOC-2026-003',
    title: 'International Oil Pollution Prevention (IOPP)',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'AMSA-IOPP-4481',
    issuingAuthority: 'AMSA',
    expiryDate: '2027-04-01',
    ocrConfidence: 92,
    complianceState: 'Mismatch/Exception',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-08-15T11:20:00Z',
        uploadedBy: 'Submitter Ops',
        fileSizeBytes: 1400000,
        fileName: 'AMSA_IOPP_4481.pdf',
        changeSummary: 'Initial statutory upload.',
      },
    ],
    vesselAttributes: {
      title: 'International Oil Pollution Prevention (IOPP)',
      certificateNumber: 'AMSA-IOPP-4481',
      certType: 'MARPOL Annex I',
      issuingBody: 'AMSA',
      issueDate: '2022-04-01',
      expiryDate: '2027-04-01',
      vesselName: 'MV Pacific Endeavour',
      imoNumber: '9123456',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2025-04-01',
      ocrConfidence: 92,
      status: 'Mismatch/Exception',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: false,
      exceptionDetails: 'OWS 15ppm calibration tag photo scan blurred.',
    },
    verificationStatus: 'Correction Requested',
    verificationNotes: 'Please upload clean high-res photo of OWS calibration certificate tag.',
  },
  {
    id: 'DOC-2026-004',
    title: 'STCW Master Unlimited CoC',
    entityType: 'Crew Certificate',
    vesselId: 'VESSEL-001',
    certificateNo: 'AMSA-STCW-88391',
    issuingAuthority: 'AMSA',
    expiryDate: '2028-09-30',
    ocrConfidence: 99,
    complianceState: 'Valid',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-09-01T09:00:00Z',
        uploadedBy: 'Crewing Administrator',
        fileSizeBytes: 980000,
        fileName: 'Master_CoC_James_Stirling.pdf',
        changeSummary: 'Initial crew credential upload.',
      },
    ],
    crewAttributes: {
      crewName: 'Capt. James Stirling',
      passportId: 'PA-983421',
      rank: 'Master Unlimited',
      certType: 'STCW Reg II/2 Master CoC',
      issuingCenter: 'Australian Maritime Safety Authority (AMSA)',
      issueDate: '2023-09-30',
      expiryDate: '2028-09-30',
      assignedVessel: 'MV Pacific Endeavour',
      nationality: 'Australian',
      trainingDate: '2023-08-15',
      ocrConfidence: 99,
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Verified',
    verificationNotes: 'AMSA public portal CoC verification match confirmed.',
  },
  {
    id: 'DOC-2026-005',
    title: 'Certificate of Class',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-002',
    certificateNo: 'LR-CLASS-88301',
    issuingAuthority: "Lloyd's Register",
    expiryDate: '2029-03-01',
    ocrConfidence: 97,
    complianceState: 'Valid',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-08-20T14:00:00Z',
        uploadedBy: 'Provider Admin',
        fileSizeBytes: 3100000,
        fileName: 'LR_Class_Cert_Coral_Titan.pdf',
        changeSummary: 'Master document vault upload.',
      },
    ],
    vesselAttributes: {
      title: 'Certificate of Class',
      certificateNumber: 'LR-CLASS-88301',
      certType: 'Class Certificate (AHTS)',
      issuingBody: "Lloyd's Register",
      issueDate: '2024-03-01',
      expiryDate: '2029-03-01',
      vesselName: 'MV Coral Titan',
      imoNumber: '9284710',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2026-02-28',
      ocrConfidence: 97,
      status: 'Valid',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Pending',
  },
  {
    id: 'DOC-2026-006',
    title: 'Certificate of Registry',
    entityType: 'Vessel Certificate',
    vesselId: 'VESSEL-003',
    certificateNo: 'REG-DARWIN-2018-12',
    issuingAuthority: 'Australian Register of Ships',
    expiryDate: '2030-05-31',
    ocrConfidence: 95,
    complianceState: 'Valid',
    currentVersion: 'v1.0',
    versions: [
      {
        versionLabel: 'v1.0',
        uploadedAt: '2026-09-02T16:45:00Z',
        uploadedBy: 'Submitter Ops',
        fileSizeBytes: 1200000,
        fileName: 'Registry_Cert_Tasman_Pioneer.pdf',
        changeSummary: 'Initial upload.',
      },
    ],
    vesselAttributes: {
      title: 'Certificate of Registry',
      certificateNumber: 'REG-DARWIN-2018-12',
      certType: 'Statutory Registry',
      issuingBody: 'Australian Register of Ships',
      issueDate: '2018-06-01',
      expiryDate: '2030-05-31',
      vesselName: 'MV Tasman Pioneer',
      imoNumber: '9648102',
      flagState: 'Australia',
      assetMatchFlag: true,
      lastSurveyDate: '2023-06-01',
      ocrConfidence: 95,
      status: 'Valid',
    },
    validationRules: {
      charterBufferPassed: true,
      assetMatch100Percent: true,
      iacsAuthorityValid: true,
      overallValid: true,
    },
    verificationStatus: 'Pending',
  },
];

export const MOCK_AUDIT_TRAIL: AuditTrailEvent[] = [
  {
    id: 'AUD-90481',
    timestampUtc: '2026-09-19T08:15:30Z',
    userId: 'USR-ADMIN-01',
    userRole: 'Administrator',
    organization: 'Pacific Ocean Logistics Pty Ltd',
    action: 'Registered Unique Vessel Record',
    targetAsset: 'MV Pacific Endeavour (IMO 9123456)',
    justificationNotes: 'Initial vessel registration across all 11 particulars categories.',
  },
  {
    id: 'AUD-90482',
    timestampUtc: '2026-09-19T09:22:10Z',
    userId: 'USR-CADMIN-02',
    userRole: 'C Admin',
    organization: 'Chevron Australia Pty Ltd',
    action: 'Initiated Assurance Set',
    targetAsset: 'AS-2026-001 (Chevron Gorgon Charter Vetting)',
    justificationNotes: 'Initiated client-driven vetting for upcoming offshore campaign.',
  },
  {
    id: 'AUD-90483',
    timestampUtc: '2026-09-19T10:05:44Z',
    userId: 'USR-SUBMIT-01',
    userRole: 'Submitter',
    organization: 'Pacific Ocean Logistics Pty Ltd',
    action: 'Uploaded Document Revision v1.1',
    targetAsset: 'DOC-2026-001 (Certificate of Class)',
    fieldDelta: {
      fieldName: 'Version',
      oldValue: 'v1.0',
      newValue: 'v1.1',
    },
    documentStatusDelta: {
      documentId: 'DOC-2026-001',
      oldStatus: 'Correction Requested',
      newStatus: 'Pending Verification',
    },
    justificationNotes: 'Re-uploaded high-res scan following verifier feedback.',
  },
  {
    id: 'AUD-90484',
    timestampUtc: '2026-09-19T11:40:12Z',
    userId: 'USR-VERIFY-01',
    userRole: 'Verifier',
    organization: 'DNV Compliance Services',
    action: 'Verified Statutory Certificate',
    targetAsset: 'DOC-2026-001 (Certificate of Class)',
    documentStatusDelta: {
      documentId: 'DOC-2026-001',
      oldStatus: 'Pending Verification',
      newStatus: 'Verified',
    },
    justificationNotes: 'Confirmed 100% identity match and valid IACS registry entry.',
  },
  {
    id: 'AUD-90485',
    timestampUtc: '2026-09-19T14:10:00Z',
    userId: 'USR-INSPEC-01',
    userRole: 'Inspector',
    organization: 'AMSA Marine Audit Division',
    action: 'Completed On-Site Survey Checklist',
    targetAsset: 'AS-2026-001 (MV Pacific Endeavour)',
    justificationNotes: 'LSA and machinery inspection passed with 1 minor CAPA deficiency.',
  },
];
